#!/usr/bin/env bash

brew install https://raw.github.com/synctree/rmi/develop/homebrews/mysql/5.1.59/mysql.rb
curl -L https://raw.github.com/synctree/rmi/develop/config/my.cnf > /usr/local/etc/my.cnf
mysql_install_db --verbose --user=`whoami` --basedir="/usr/local/Cellar/mysql/5.1.59" --datadir=/usr/local/var/mysql --tmpdir=/tmp
mkdir -p ~/Library/LaunchAgents
cp /usr/local/Cellar/mysql/5.1.59/com.mysql.mysqld.plist ~/Library/LaunchAgents/
launchctl unload -w ~/Library/LaunchAgents/com.mysql.mysqld.plist > /dev/null 2>&1 || true
launchctl load -w ~/Library/LaunchAgents/com.mysql.mysqld.plist