#!/usr/bin/env bash

brew install https://raw.github.com/synctree/rmi/develop/homebrews/redis/2.4.13/redis.rb
mkdir -p ~/Library/LaunchAgents
cp /usr/local/Cellar/redis/2.4.13/homebrew.mxcl.redis.plist ~/Library/LaunchAgents/
launchctl unload -w ~/Library/LaunchAgents/homebrew.mxcl.redis.plist > /dev/null 2>&1 || true
launchctl load -w ~/Library/LaunchAgents/homebrew.mxcl.redis.plist